# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: watcher.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from tap_e2e.proto import device_pb2 as device__pb2
from tap_e2e.proto import watch_pb2 as watch__pb2
from . import watcher_pb2 as watcher__pb2


class WatcherService(Protocol):
    async def status(self, request: watcher__pb2.StatusRequest, ctx: RequestContext) -> watcher__pb2.StatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_devices(self, request: device__pb2.ListDevicesRequest, ctx: RequestContext) -> device__pb2.ListDevicesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def watch(self, request: watch__pb2.WatchRequest, ctx: RequestContext) -> AsyncIterator[watch__pb2.WatchResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def watch_video(self, request: watch__pb2.WatchVideoRequest, ctx: RequestContext) -> AsyncIterator[watch__pb2.WatchVideoResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def start_recording(self, request: watcher__pb2.StartRecordingRequest, ctx: RequestContext) -> watcher__pb2.StartRecordingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def stop_recording(self, request: watcher__pb2.StopRecordingRequest, ctx: RequestContext) -> watcher__pb2.StopRecordingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def save_clip(self, request: watcher__pb2.SaveClipRequest, ctx: RequestContext) -> watcher__pb2.SaveClipResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_recordings(self, request: watcher__pb2.ListRecordingsRequest, ctx: RequestContext) -> watcher__pb2.ListRecordingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_recordings(self, request: watcher__pb2.DeleteRecordingsRequest, ctx: RequestContext) -> watcher__pb2.DeleteRecordingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WatcherServiceASGIApplication(ConnectASGIApplication[WatcherService]):
    def __init__(self, service: WatcherService | AsyncGenerator[WatcherService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tap.watcher.v1.WatcherService/Status": Endpoint.unary(
                    method=MethodInfo(
                        name="Status",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.StatusRequest,
                        output=watcher__pb2.StatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.status,
                ),
                "/tap.watcher.v1.WatcherService/ListDevices": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDevices",
                        service_name="tap.watcher.v1.WatcherService",
                        input=device__pb2.ListDevicesRequest,
                        output=device__pb2.ListDevicesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_devices,
                ),
                "/tap.watcher.v1.WatcherService/Watch": Endpoint.server_stream(
                    method=MethodInfo(
                        name="Watch",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watch__pb2.WatchRequest,
                        output=watch__pb2.WatchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.watch,
                ),
                "/tap.watcher.v1.WatcherService/WatchVideo": Endpoint.server_stream(
                    method=MethodInfo(
                        name="WatchVideo",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watch__pb2.WatchVideoRequest,
                        output=watch__pb2.WatchVideoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.watch_video,
                ),
                "/tap.watcher.v1.WatcherService/StartRecording": Endpoint.unary(
                    method=MethodInfo(
                        name="StartRecording",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.StartRecordingRequest,
                        output=watcher__pb2.StartRecordingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.start_recording,
                ),
                "/tap.watcher.v1.WatcherService/StopRecording": Endpoint.unary(
                    method=MethodInfo(
                        name="StopRecording",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.StopRecordingRequest,
                        output=watcher__pb2.StopRecordingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.stop_recording,
                ),
                "/tap.watcher.v1.WatcherService/SaveClip": Endpoint.unary(
                    method=MethodInfo(
                        name="SaveClip",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.SaveClipRequest,
                        output=watcher__pb2.SaveClipResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.save_clip,
                ),
                "/tap.watcher.v1.WatcherService/ListRecordings": Endpoint.unary(
                    method=MethodInfo(
                        name="ListRecordings",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.ListRecordingsRequest,
                        output=watcher__pb2.ListRecordingsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_recordings,
                ),
                "/tap.watcher.v1.WatcherService/DeleteRecordings": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteRecordings",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.DeleteRecordingsRequest,
                        output=watcher__pb2.DeleteRecordingsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_recordings,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tap.watcher.v1.WatcherService"


class WatcherServiceClient(ConnectClient):
    async def status(
        self,
        request: watcher__pb2.StatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.StatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Status",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.StatusRequest,
                output=watcher__pb2.StatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_devices(
        self,
        request: device__pb2.ListDevicesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> device__pb2.ListDevicesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDevices",
                service_name="tap.watcher.v1.WatcherService",
                input=device__pb2.ListDevicesRequest,
                output=device__pb2.ListDevicesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def watch(
        self,
        request: watch__pb2.WatchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[watch__pb2.WatchResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Watch",
                service_name="tap.watcher.v1.WatcherService",
                input=watch__pb2.WatchRequest,
                output=watch__pb2.WatchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def watch_video(
        self,
        request: watch__pb2.WatchVideoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[watch__pb2.WatchVideoResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchVideo",
                service_name="tap.watcher.v1.WatcherService",
                input=watch__pb2.WatchVideoRequest,
                output=watch__pb2.WatchVideoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def start_recording(
        self,
        request: watcher__pb2.StartRecordingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.StartRecordingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartRecording",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.StartRecordingRequest,
                output=watcher__pb2.StartRecordingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def stop_recording(
        self,
        request: watcher__pb2.StopRecordingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.StopRecordingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StopRecording",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.StopRecordingRequest,
                output=watcher__pb2.StopRecordingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def save_clip(
        self,
        request: watcher__pb2.SaveClipRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.SaveClipResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SaveClip",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.SaveClipRequest,
                output=watcher__pb2.SaveClipResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_recordings(
        self,
        request: watcher__pb2.ListRecordingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.ListRecordingsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRecordings",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.ListRecordingsRequest,
                output=watcher__pb2.ListRecordingsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_recordings(
        self,
        request: watcher__pb2.DeleteRecordingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.DeleteRecordingsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteRecordings",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.DeleteRecordingsRequest,
                output=watcher__pb2.DeleteRecordingsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class WatcherServiceSync(Protocol):
    def status(self, request: watcher__pb2.StatusRequest, ctx: RequestContext) -> watcher__pb2.StatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_devices(self, request: device__pb2.ListDevicesRequest, ctx: RequestContext) -> device__pb2.ListDevicesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def watch(self, request: watch__pb2.WatchRequest, ctx: RequestContext) -> Iterator[watch__pb2.WatchResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def watch_video(self, request: watch__pb2.WatchVideoRequest, ctx: RequestContext) -> Iterator[watch__pb2.WatchVideoResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def start_recording(self, request: watcher__pb2.StartRecordingRequest, ctx: RequestContext) -> watcher__pb2.StartRecordingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def stop_recording(self, request: watcher__pb2.StopRecordingRequest, ctx: RequestContext) -> watcher__pb2.StopRecordingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def save_clip(self, request: watcher__pb2.SaveClipRequest, ctx: RequestContext) -> watcher__pb2.SaveClipResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_recordings(self, request: watcher__pb2.ListRecordingsRequest, ctx: RequestContext) -> watcher__pb2.ListRecordingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_recordings(self, request: watcher__pb2.DeleteRecordingsRequest, ctx: RequestContext) -> watcher__pb2.DeleteRecordingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WatcherServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: WatcherServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/tap.watcher.v1.WatcherService/Status": EndpointSync.unary(
                    method=MethodInfo(
                        name="Status",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.StatusRequest,
                        output=watcher__pb2.StatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.status,
                ),
                "/tap.watcher.v1.WatcherService/ListDevices": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDevices",
                        service_name="tap.watcher.v1.WatcherService",
                        input=device__pb2.ListDevicesRequest,
                        output=device__pb2.ListDevicesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_devices,
                ),
                "/tap.watcher.v1.WatcherService/Watch": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="Watch",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watch__pb2.WatchRequest,
                        output=watch__pb2.WatchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.watch,
                ),
                "/tap.watcher.v1.WatcherService/WatchVideo": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="WatchVideo",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watch__pb2.WatchVideoRequest,
                        output=watch__pb2.WatchVideoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.watch_video,
                ),
                "/tap.watcher.v1.WatcherService/StartRecording": EndpointSync.unary(
                    method=MethodInfo(
                        name="StartRecording",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.StartRecordingRequest,
                        output=watcher__pb2.StartRecordingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.start_recording,
                ),
                "/tap.watcher.v1.WatcherService/StopRecording": EndpointSync.unary(
                    method=MethodInfo(
                        name="StopRecording",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.StopRecordingRequest,
                        output=watcher__pb2.StopRecordingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.stop_recording,
                ),
                "/tap.watcher.v1.WatcherService/SaveClip": EndpointSync.unary(
                    method=MethodInfo(
                        name="SaveClip",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.SaveClipRequest,
                        output=watcher__pb2.SaveClipResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.save_clip,
                ),
                "/tap.watcher.v1.WatcherService/ListRecordings": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListRecordings",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.ListRecordingsRequest,
                        output=watcher__pb2.ListRecordingsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_recordings,
                ),
                "/tap.watcher.v1.WatcherService/DeleteRecordings": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteRecordings",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.DeleteRecordingsRequest,
                        output=watcher__pb2.DeleteRecordingsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_recordings,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tap.watcher.v1.WatcherService"


class WatcherServiceClientSync(ConnectClientSync):
    def status(
        self,
        request: watcher__pb2.StatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.StatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Status",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.StatusRequest,
                output=watcher__pb2.StatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_devices(
        self,
        request: device__pb2.ListDevicesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> device__pb2.ListDevicesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDevices",
                service_name="tap.watcher.v1.WatcherService",
                input=device__pb2.ListDevicesRequest,
                output=device__pb2.ListDevicesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def watch(
        self,
        request: watch__pb2.WatchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[watch__pb2.WatchResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Watch",
                service_name="tap.watcher.v1.WatcherService",
                input=watch__pb2.WatchRequest,
                output=watch__pb2.WatchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def watch_video(
        self,
        request: watch__pb2.WatchVideoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[watch__pb2.WatchVideoResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchVideo",
                service_name="tap.watcher.v1.WatcherService",
                input=watch__pb2.WatchVideoRequest,
                output=watch__pb2.WatchVideoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def start_recording(
        self,
        request: watcher__pb2.StartRecordingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.StartRecordingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartRecording",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.StartRecordingRequest,
                output=watcher__pb2.StartRecordingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def stop_recording(
        self,
        request: watcher__pb2.StopRecordingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.StopRecordingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StopRecording",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.StopRecordingRequest,
                output=watcher__pb2.StopRecordingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def save_clip(
        self,
        request: watcher__pb2.SaveClipRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.SaveClipResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SaveClip",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.SaveClipRequest,
                output=watcher__pb2.SaveClipResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_recordings(
        self,
        request: watcher__pb2.ListRecordingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.ListRecordingsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRecordings",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.ListRecordingsRequest,
                output=watcher__pb2.ListRecordingsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_recordings(
        self,
        request: watcher__pb2.DeleteRecordingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.DeleteRecordingsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteRecordings",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.DeleteRecordingsRequest,
                output=watcher__pb2.DeleteRecordingsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
