# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: watcher.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'watcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tap_e2e.proto import client_connection_pb2 as client__connection__pb2
from tap_e2e.proto import device_pb2 as device__pb2
from tap_e2e.proto import video_pb2 as video__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwatcher.proto\x12\x0etap.watcher.v1\x1a\x17\x63lient_connection.proto\x1a\x0c\x64\x65vice.proto\x1a\x0bvideo.proto\"\x14\n\x12ListDevicesRequest\"i\n\x13ListDevicesResponse\x12$\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x13.tap.v1.DeviceEntry\x12,\n\x0b\x63onnections\x18\x02 \x03(\x0b\x32\x17.tap.v1.ConnectionEntry\"G\n\x12WatchEventsRequest\x12\x1e\n\x16observed_connection_id\x18\x01 \x01(\t\x12\x11\n\tafter_seq\x18\x02 \x01(\x03\"B\n\x13WatchEventsResponse\x12+\n\x06update\x18\x01 \x01(\x0b\x32\x1b.tap.v1.WatchEventsResponse2\x89\x02\n\x0eWatcherService\x12V\n\x0bListDevices\x12\".tap.watcher.v1.ListDevicesRequest\x1a#.tap.watcher.v1.ListDevicesResponse\x12X\n\x0bWatchEvents\x12\".tap.watcher.v1.WatchEventsRequest\x1a#.tap.watcher.v1.WatchEventsResponse0\x01\x12\x45\n\nWatchVideo\x12\x19.tap.v1.WatchVideoRequest\x1a\x1a.tap.v1.WatchVideoResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTDEVICESREQUEST']._serialized_start=85
  _globals['_LISTDEVICESREQUEST']._serialized_end=105
  _globals['_LISTDEVICESRESPONSE']._serialized_start=107
  _globals['_LISTDEVICESRESPONSE']._serialized_end=212
  _globals['_WATCHEVENTSREQUEST']._serialized_start=214
  _globals['_WATCHEVENTSREQUEST']._serialized_end=285
  _globals['_WATCHEVENTSRESPONSE']._serialized_start=287
  _globals['_WATCHEVENTSRESPONSE']._serialized_end=353
  _globals['_WATCHERSERVICE']._serialized_start=356
  _globals['_WATCHERSERVICE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
