# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: watcher.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from tap_e2e.proto import video_pb2 as video__pb2
from . import watcher_pb2 as watcher__pb2


class WatcherService(Protocol):
    async def list_devices(self, request: watcher__pb2.ListDevicesRequest, ctx: RequestContext) -> watcher__pb2.ListDevicesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def watch_events(self, request: watcher__pb2.WatchEventsRequest, ctx: RequestContext) -> AsyncIterator[watcher__pb2.WatchEventsResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def watch_video(self, request: video__pb2.WatchVideoRequest, ctx: RequestContext) -> AsyncIterator[video__pb2.WatchVideoResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WatcherServiceASGIApplication(ConnectASGIApplication[WatcherService]):
    def __init__(self, service: WatcherService | AsyncGenerator[WatcherService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tap.watcher.v1.WatcherService/ListDevices": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDevices",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.ListDevicesRequest,
                        output=watcher__pb2.ListDevicesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_devices,
                ),
                "/tap.watcher.v1.WatcherService/WatchEvents": Endpoint.server_stream(
                    method=MethodInfo(
                        name="WatchEvents",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.WatchEventsRequest,
                        output=watcher__pb2.WatchEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.watch_events,
                ),
                "/tap.watcher.v1.WatcherService/WatchVideo": Endpoint.server_stream(
                    method=MethodInfo(
                        name="WatchVideo",
                        service_name="tap.watcher.v1.WatcherService",
                        input=video__pb2.WatchVideoRequest,
                        output=video__pb2.WatchVideoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.watch_video,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tap.watcher.v1.WatcherService"


class WatcherServiceClient(ConnectClient):
    async def list_devices(
        self,
        request: watcher__pb2.ListDevicesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.ListDevicesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDevices",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.ListDevicesRequest,
                output=watcher__pb2.ListDevicesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def watch_events(
        self,
        request: watcher__pb2.WatchEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[watcher__pb2.WatchEventsResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchEvents",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.WatchEventsRequest,
                output=watcher__pb2.WatchEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def watch_video(
        self,
        request: video__pb2.WatchVideoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[video__pb2.WatchVideoResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchVideo",
                service_name="tap.watcher.v1.WatcherService",
                input=video__pb2.WatchVideoRequest,
                output=video__pb2.WatchVideoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class WatcherServiceSync(Protocol):
    def list_devices(self, request: watcher__pb2.ListDevicesRequest, ctx: RequestContext) -> watcher__pb2.ListDevicesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def watch_events(self, request: watcher__pb2.WatchEventsRequest, ctx: RequestContext) -> Iterator[watcher__pb2.WatchEventsResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def watch_video(self, request: video__pb2.WatchVideoRequest, ctx: RequestContext) -> Iterator[video__pb2.WatchVideoResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WatcherServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: WatcherServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/tap.watcher.v1.WatcherService/ListDevices": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDevices",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.ListDevicesRequest,
                        output=watcher__pb2.ListDevicesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_devices,
                ),
                "/tap.watcher.v1.WatcherService/WatchEvents": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="WatchEvents",
                        service_name="tap.watcher.v1.WatcherService",
                        input=watcher__pb2.WatchEventsRequest,
                        output=watcher__pb2.WatchEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.watch_events,
                ),
                "/tap.watcher.v1.WatcherService/WatchVideo": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="WatchVideo",
                        service_name="tap.watcher.v1.WatcherService",
                        input=video__pb2.WatchVideoRequest,
                        output=video__pb2.WatchVideoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.watch_video,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tap.watcher.v1.WatcherService"


class WatcherServiceClientSync(ConnectClientSync):
    def list_devices(
        self,
        request: watcher__pb2.ListDevicesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> watcher__pb2.ListDevicesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDevices",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.ListDevicesRequest,
                output=watcher__pb2.ListDevicesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def watch_events(
        self,
        request: watcher__pb2.WatchEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[watcher__pb2.WatchEventsResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchEvents",
                service_name="tap.watcher.v1.WatcherService",
                input=watcher__pb2.WatchEventsRequest,
                output=watcher__pb2.WatchEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def watch_video(
        self,
        request: video__pb2.WatchVideoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[video__pb2.WatchVideoResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchVideo",
                service_name="tap.watcher.v1.WatcherService",
                input=video__pb2.WatchVideoRequest,
                output=video__pb2.WatchVideoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
