# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: studio.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from . import studio_pb2 as studio__pb2


class StudioService(Protocol):
    async def info(self, request: studio__pb2.InfoRequest, ctx: RequestContext) -> studio__pb2.InfoResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_recording(self, request: studio__pb2.GetRecordingRequest, ctx: RequestContext) -> studio__pb2.GetRecordingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class StudioServiceASGIApplication(ConnectASGIApplication[StudioService]):
    def __init__(self, service: StudioService | AsyncGenerator[StudioService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tap.studio.v1.StudioService/Info": Endpoint.unary(
                    method=MethodInfo(
                        name="Info",
                        service_name="tap.studio.v1.StudioService",
                        input=studio__pb2.InfoRequest,
                        output=studio__pb2.InfoResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.info,
                ),
                "/tap.studio.v1.StudioService/GetRecording": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRecording",
                        service_name="tap.studio.v1.StudioService",
                        input=studio__pb2.GetRecordingRequest,
                        output=studio__pb2.GetRecordingResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_recording,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tap.studio.v1.StudioService"


class StudioServiceClient(ConnectClient):
    async def info(
        self,
        request: studio__pb2.InfoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> studio__pb2.InfoResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Info",
                service_name="tap.studio.v1.StudioService",
                input=studio__pb2.InfoRequest,
                output=studio__pb2.InfoResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_recording(
        self,
        request: studio__pb2.GetRecordingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> studio__pb2.GetRecordingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRecording",
                service_name="tap.studio.v1.StudioService",
                input=studio__pb2.GetRecordingRequest,
                output=studio__pb2.GetRecordingResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )


class StudioServiceSync(Protocol):
    def info(self, request: studio__pb2.InfoRequest, ctx: RequestContext) -> studio__pb2.InfoResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_recording(self, request: studio__pb2.GetRecordingRequest, ctx: RequestContext) -> studio__pb2.GetRecordingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class StudioServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: StudioServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/tap.studio.v1.StudioService/Info": EndpointSync.unary(
                    method=MethodInfo(
                        name="Info",
                        service_name="tap.studio.v1.StudioService",
                        input=studio__pb2.InfoRequest,
                        output=studio__pb2.InfoResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.info,
                ),
                "/tap.studio.v1.StudioService/GetRecording": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRecording",
                        service_name="tap.studio.v1.StudioService",
                        input=studio__pb2.GetRecordingRequest,
                        output=studio__pb2.GetRecordingResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_recording,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tap.studio.v1.StudioService"


class StudioServiceClientSync(ConnectClientSync):
    def info(
        self,
        request: studio__pb2.InfoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> studio__pb2.InfoResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Info",
                service_name="tap.studio.v1.StudioService",
                input=studio__pb2.InfoRequest,
                output=studio__pb2.InfoResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def get_recording(
        self,
        request: studio__pb2.GetRecordingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> studio__pb2.GetRecordingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRecording",
                service_name="tap.studio.v1.StudioService",
                input=studio__pb2.GetRecordingRequest,
                output=studio__pb2.GetRecordingResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
