#!/usr/bin/env python3
"""Generate committed watcher Python/TypeScript protobuf bindings (or verify --check)."""

from __future__ import annotations

import filecmp
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
from importlib.metadata import version

CLIENT = pathlib.Path(__file__).resolve().parents[1]
CONTRACTS = CLIENT.parents[1] / "contracts" / "proto"
PY_OUT = CLIENT / "tap_watcher" / "_gen"
TS_OUT = CLIENT / "web" / "src" / "gen"
ES = CLIENT / "web" / "node_modules" / ".bin" / "protoc-gen-es"


def generate(py_out: pathlib.Path, ts_out: pathlib.Path) -> None:
    """Generate both languages, sharing tap-e2e's schema registry in Python."""
    for path in (py_out, ts_out):
        path.mkdir(parents=True, exist_ok=True)
    proto = CLIENT / "proto" / "watcher.proto"
    base = [
        sys.executable,
        "-m",
        "grpc_tools.protoc",
        f"-I{proto.parent}",
        f"-I{CONTRACTS}",
    ]
    connect = pathlib.Path(sys.executable).parent / "protoc-gen-connect-python"
    subprocess.run(
        [
            *base,
            f"--python_out={py_out}",
            f"--pyi_out={py_out}",
            f"--plugin=protoc-gen-connect-python={connect}",
            f"--connect-python_out={py_out}",
            str(proto),
        ],
        check=True,
    )
    pattern = re.compile(r"^import (\w+_pb2) as (\w+)$", re.MULTILINE)
    for path in py_out.glob("watcher_*.py*"):
        content = pattern.sub(
            lambda m: (
                f"from . import {m[1]} as {m[2]}"
                if m[1] == "watcher_pb2"
                else f"from tap_e2e.proto import {m[1]} as {m[2]}"
            ),
            path.read_text(),
        )
        if path.suffix == ".pyi":
            content = "# ruff: noqa\n" + content
        path.write_text(content)
    (py_out / "__init__.py").write_text(
        "# Generated by scripts/gen_protos.py; do not edit.\n"
    )
    subprocess.run(
        [
            *base,
            f"--plugin=protoc-gen-es={ES}",
            f"--es_out={ts_out}",
            "--es_opt=target=ts,import_extension=none",
            str(proto),
            *map(str, sorted(CONTRACTS.glob("*.proto"))),
        ],
        check=True,
    )


def main() -> int:
    """Regenerate outputs, or check byte-for-byte against the pinned generators."""
    if sys.argv[1:] not in ([], ["--check"]):
        raise SystemExit("usage: gen_protos.py [--check]")
    for name, wanted in {
        "grpcio-tools": "1.84.0",
        "protoc-gen-connect-python": "0.9.0",
    }.items():
        if version(name) != wanted:
            raise SystemExit(f"{name} must be {wanted}")
    if not ES.exists():
        raise SystemExit("run bun install in clients/watcher/web first")
    if "--check" in sys.argv:
        with tempfile.TemporaryDirectory() as root:
            py, ts = pathlib.Path(root, "py"), pathlib.Path(root, "ts")
            generate(py, ts)
            for fresh, committed in ((py, PY_OUT), (ts, TS_OUT)):
                names = {p.name for p in fresh.iterdir()} | {
                    p.name for p in committed.iterdir() if p.is_file()
                }
                for name in names:
                    if (
                        not (fresh / name).is_file()
                        or not (committed / name).is_file()
                        or not filecmp.cmp(
                            fresh / name, committed / name, shallow=False
                        )
                    ):
                        raise SystemExit(f"stale generated code: {committed / name}")
    else:
        for path in (PY_OUT, TS_OUT):
            shutil.rmtree(path, ignore_errors=True)
        generate(PY_OUT, TS_OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
