plugins {
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.kotlin.plugin.serialization")
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.0")
    // RE2 regex for user selectors: linear time, no backreferences/lookaround (plan §10).
    api("com.google.re2j:re2j:1.8")

    testImplementation(kotlin("test"))
}

/*
 * The engine version (gradle.properties `tap.version.engine`) is compiled in as
 * `ENGINE_VERSION`, which the host and driver build ids and the service version derive from.
 */
val generateEngineVersion by tasks.registering {
    val version = project.version.toString()
    val outDir = layout.buildDirectory.dir("generated/engine-version")
    inputs.property("version", version)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().file("io/github/noamcohen48/tap/protocol/EngineVersion.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by :contracts:protocol from gradle.properties; do not edit.
            |package io.github.noamcohen48.tap.protocol
            |
            |/** Version of the engine (service, bundled driver, protocol, tap-api). */
            |const val ENGINE_VERSION = "$version"
            |""".trimMargin(),
        )
    }
}

kotlin.sourceSets.main { kotlin.srcDir(generateEngineVersion) }

tasks.test {
    useJUnitPlatform()
    // `./gradlew :contracts:protocol:test -Dtap.golden.update=true` rewrites the golden wire fixtures.
    systemProperty("tap.golden.update", System.getProperty("tap.golden.update") ?: "false")
}
