# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import device_pb2 as device__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/tap.v1.DeviceService/ListDevices',
                request_serializer=device__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=device__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.Attach = channel.unary_unary(
                '/tap.v1.DeviceService/Attach',
                request_serializer=device__pb2.AttachRequest.SerializeToString,
                response_deserializer=device__pb2.AttachResponse.FromString,
                _registered_method=True)
        self.Detach = channel.unary_unary(
                '/tap.v1.DeviceService/Detach',
                request_serializer=device__pb2.DetachRequest.SerializeToString,
                response_deserializer=device__pb2.DetachResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/tap.v1.DeviceService/Execute',
                request_serializer=device__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=device__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Screenshot = channel.unary_unary(
                '/tap.v1.DeviceService/Screenshot',
                request_serializer=device__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=device__pb2.ScreenshotResponse.FromString,
                _registered_method=True)
        self.DriverLog = channel.unary_unary(
                '/tap.v1.DeviceService/DriverLog',
                request_serializer=device__pb2.DriverLogRequest.SerializeToString,
                response_deserializer=device__pb2.DriverLogResponse.FromString,
                _registered_method=True)
        self.StartRecording = channel.unary_unary(
                '/tap.v1.DeviceService/StartRecording',
                request_serializer=device__pb2.StartRecordingRequest.SerializeToString,
                response_deserializer=device__pb2.StartRecordingResponse.FromString,
                _registered_method=True)
        self.StopRecording = channel.unary_unary(
                '/tap.v1.DeviceService/StopRecording',
                request_serializer=device__pb2.StopRecordingRequest.SerializeToString,
                response_deserializer=device__pb2.StopRecordingResponse.FromString,
                _registered_method=True)
        self.ScreenSnapshot = channel.unary_unary(
                '/tap.v1.DeviceService/ScreenSnapshot',
                request_serializer=device__pb2.ScreenSnapshotRequest.SerializeToString,
                response_deserializer=device__pb2.ScreenSnapshotResponse.FromString,
                _registered_method=True)
        self.ResolveRef = channel.unary_unary(
                '/tap.v1.DeviceService/ResolveRef',
                request_serializer=device__pb2.ResolveRefRequest.SerializeToString,
                response_deserializer=device__pb2.ResolveRefResponse.FromString,
                _registered_method=True)
        self.SetAnimations = channel.unary_unary(
                '/tap.v1.DeviceService/SetAnimations',
                request_serializer=device__pb2.SetAnimationsRequest.SerializeToString,
                response_deserializer=device__pb2.SetAnimationsResponse.FromString,
                _registered_method=True)
        self.SetDarkMode = channel.unary_unary(
                '/tap.v1.DeviceService/SetDarkMode',
                request_serializer=device__pb2.SetDarkModeRequest.SerializeToString,
                response_deserializer=device__pb2.SetDarkModeResponse.FromString,
                _registered_method=True)
        self.SetFontScale = channel.unary_unary(
                '/tap.v1.DeviceService/SetFontScale',
                request_serializer=device__pb2.SetFontScaleRequest.SerializeToString,
                response_deserializer=device__pb2.SetFontScaleResponse.FromString,
                _registered_method=True)
        self.SetDensity = channel.unary_unary(
                '/tap.v1.DeviceService/SetDensity',
                request_serializer=device__pb2.SetDensityRequest.SerializeToString,
                response_deserializer=device__pb2.SetDensityResponse.FromString,
                _registered_method=True)
        self.SetNetwork = channel.unary_unary(
                '/tap.v1.DeviceService/SetNetwork',
                request_serializer=device__pb2.SetNetworkRequest.SerializeToString,
                response_deserializer=device__pb2.SetNetworkResponse.FromString,
                _registered_method=True)
        self.SetSystemLocales = channel.unary_unary(
                '/tap.v1.DeviceService/SetSystemLocales',
                request_serializer=device__pb2.SetSystemLocalesRequest.SerializeToString,
                response_deserializer=device__pb2.SetSystemLocalesResponse.FromString,
                _registered_method=True)
        self.SetLocation = channel.unary_unary(
                '/tap.v1.DeviceService/SetLocation',
                request_serializer=device__pb2.SetLocationRequest.SerializeToString,
                response_deserializer=device__pb2.SetLocationResponse.FromString,
                _registered_method=True)


class DeviceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attach(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detach(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Screenshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DriverLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRecording(self, request, context):
        """One optional host-managed scrcpy capture per attachment (video, audio or both); the driver
        never encodes media. Requires scrcpy on the daemon host.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScreenSnapshot(self, request, context):
        """A compact, ref-addressed outline of the screen, parsed from the diagnostic hierarchy dump
        (`.docs/agent-surface.md`). Refs name selectors the daemon synthesised, never node handles.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveRef(self, request, context):
        """The selector a ref of the latest snapshot names. Unknown ref: NOT_FOUND (UNKNOWN_REF);
        a node with no selector: FAILED_PRECONDITION (REF_NOT_ADDRESSABLE).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAnimations(self, request, context):
        """Device-wide conditions. Each changed value is captured before the session's first change
        of it, journaled, and restored when the device is detached (or by the next attach when the
        daemon died first); a restore that cannot be proven quarantines the device. Every change is
        read back: a value the device did not take is FAILED_PRECONDITION (DEVICE_SETTING).
        The three animation scales (window, transition, animator duration): all 0 or all 1.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDarkMode(self, request, context):
        """`cmd uimode night yes|no`. API 29+ (FAILED_PRECONDITION, UNSUPPORTED_API below).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFontScale(self, request, context):
        """The system font scale (`font_scale`), 0.5 to 2.0.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDensity(self, request, context):
        """`wm density`: an override in dpi (100 to 1000), or absent for the display's physical density.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNetwork(self, request, context):
        """Airplane mode (`cmd connectivity airplane-mode`), Wi-Fi (`svc wifi`) and mobile data
        (`svc data`): the real switches, nothing mocked. API 29+. Airplane mode is written first;
        all three are captured on the first change and restored airplane mode first. A device reached
        over ADB on the network refuses Wi-Fi off / airplane mode on (FAILED_PRECONDITION).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSystemLocales(self, request, context):
        """The device-wide locale list (Settings › Languages), 1 to 16 BCP-47 tags in preference order
        (INVALID_ARGUMENT otherwise). Android has no shell command for it: the driver app applies it
        as Settings' language picker does, and it is read back (`system_locales`).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLocation(self, request, context):
        """Mock location: the device reports this fix from its location providers until detach.
        `latitude` -90..90, `longitude` -180..180, `accuracy_m` > 0 (default 5), `altitude_m` finite
        (INVALID_ARGUMENT otherwise). The driver app becomes the mock-location app (its
        `android:mock_location` app-op) and location is turned on when it is off; both are captured
        and restored on detach, which ends the mock. The driver serves the fix (`set_location`).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=device__pb2.ListDevicesRequest.FromString,
                    response_serializer=device__pb2.ListDevicesResponse.SerializeToString,
            ),
            'Attach': grpc.unary_unary_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=device__pb2.AttachRequest.FromString,
                    response_serializer=device__pb2.AttachResponse.SerializeToString,
            ),
            'Detach': grpc.unary_unary_rpc_method_handler(
                    servicer.Detach,
                    request_deserializer=device__pb2.DetachRequest.FromString,
                    response_serializer=device__pb2.DetachResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=device__pb2.ExecuteRequest.FromString,
                    response_serializer=device__pb2.ExecuteResponse.SerializeToString,
            ),
            'Screenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Screenshot,
                    request_deserializer=device__pb2.ScreenshotRequest.FromString,
                    response_serializer=device__pb2.ScreenshotResponse.SerializeToString,
            ),
            'DriverLog': grpc.unary_unary_rpc_method_handler(
                    servicer.DriverLog,
                    request_deserializer=device__pb2.DriverLogRequest.FromString,
                    response_serializer=device__pb2.DriverLogResponse.SerializeToString,
            ),
            'StartRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRecording,
                    request_deserializer=device__pb2.StartRecordingRequest.FromString,
                    response_serializer=device__pb2.StartRecordingResponse.SerializeToString,
            ),
            'StopRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRecording,
                    request_deserializer=device__pb2.StopRecordingRequest.FromString,
                    response_serializer=device__pb2.StopRecordingResponse.SerializeToString,
            ),
            'ScreenSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ScreenSnapshot,
                    request_deserializer=device__pb2.ScreenSnapshotRequest.FromString,
                    response_serializer=device__pb2.ScreenSnapshotResponse.SerializeToString,
            ),
            'ResolveRef': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveRef,
                    request_deserializer=device__pb2.ResolveRefRequest.FromString,
                    response_serializer=device__pb2.ResolveRefResponse.SerializeToString,
            ),
            'SetAnimations': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAnimations,
                    request_deserializer=device__pb2.SetAnimationsRequest.FromString,
                    response_serializer=device__pb2.SetAnimationsResponse.SerializeToString,
            ),
            'SetDarkMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDarkMode,
                    request_deserializer=device__pb2.SetDarkModeRequest.FromString,
                    response_serializer=device__pb2.SetDarkModeResponse.SerializeToString,
            ),
            'SetFontScale': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFontScale,
                    request_deserializer=device__pb2.SetFontScaleRequest.FromString,
                    response_serializer=device__pb2.SetFontScaleResponse.SerializeToString,
            ),
            'SetDensity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDensity,
                    request_deserializer=device__pb2.SetDensityRequest.FromString,
                    response_serializer=device__pb2.SetDensityResponse.SerializeToString,
            ),
            'SetNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNetwork,
                    request_deserializer=device__pb2.SetNetworkRequest.FromString,
                    response_serializer=device__pb2.SetNetworkResponse.SerializeToString,
            ),
            'SetSystemLocales': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSystemLocales,
                    request_deserializer=device__pb2.SetSystemLocalesRequest.FromString,
                    response_serializer=device__pb2.SetSystemLocalesResponse.SerializeToString,
            ),
            'SetLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLocation,
                    request_deserializer=device__pb2.SetLocationRequest.FromString,
                    response_serializer=device__pb2.SetLocationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tap.v1.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tap.v1.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/ListDevices',
            device__pb2.ListDevicesRequest.SerializeToString,
            device__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/Attach',
            device__pb2.AttachRequest.SerializeToString,
            device__pb2.AttachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Detach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/Detach',
            device__pb2.DetachRequest.SerializeToString,
            device__pb2.DetachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/Execute',
            device__pb2.ExecuteRequest.SerializeToString,
            device__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Screenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/Screenshot',
            device__pb2.ScreenshotRequest.SerializeToString,
            device__pb2.ScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DriverLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/DriverLog',
            device__pb2.DriverLogRequest.SerializeToString,
            device__pb2.DriverLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/StartRecording',
            device__pb2.StartRecordingRequest.SerializeToString,
            device__pb2.StartRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/StopRecording',
            device__pb2.StopRecordingRequest.SerializeToString,
            device__pb2.StopRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScreenSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/ScreenSnapshot',
            device__pb2.ScreenSnapshotRequest.SerializeToString,
            device__pb2.ScreenSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveRef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/ResolveRef',
            device__pb2.ResolveRefRequest.SerializeToString,
            device__pb2.ResolveRefResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAnimations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/SetAnimations',
            device__pb2.SetAnimationsRequest.SerializeToString,
            device__pb2.SetAnimationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDarkMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/SetDarkMode',
            device__pb2.SetDarkModeRequest.SerializeToString,
            device__pb2.SetDarkModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFontScale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/SetFontScale',
            device__pb2.SetFontScaleRequest.SerializeToString,
            device__pb2.SetFontScaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDensity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/SetDensity',
            device__pb2.SetDensityRequest.SerializeToString,
            device__pb2.SetDensityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/SetNetwork',
            device__pb2.SetNetworkRequest.SerializeToString,
            device__pb2.SetNetworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSystemLocales(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/SetSystemLocales',
            device__pb2.SetSystemLocalesRequest.SerializeToString,
            device__pb2.SetSystemLocalesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/SetLocation',
            device__pb2.SetLocationRequest.SerializeToString,
            device__pb2.SetLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
