# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import device_pb2 as device__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/tap.v1.DeviceService/ListDevices',
                request_serializer=device__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=device__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.Attach = channel.unary_unary(
                '/tap.v1.DeviceService/Attach',
                request_serializer=device__pb2.AttachRequest.SerializeToString,
                response_deserializer=device__pb2.AttachResponse.FromString,
                _registered_method=True)
        self.Detach = channel.unary_unary(
                '/tap.v1.DeviceService/Detach',
                request_serializer=device__pb2.DetachRequest.SerializeToString,
                response_deserializer=device__pb2.DetachResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/tap.v1.DeviceService/Execute',
                request_serializer=device__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=device__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Screenshot = channel.unary_unary(
                '/tap.v1.DeviceService/Screenshot',
                request_serializer=device__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=device__pb2.ScreenshotResponse.FromString,
                _registered_method=True)
        self.DriverLog = channel.unary_unary(
                '/tap.v1.DeviceService/DriverLog',
                request_serializer=device__pb2.DriverLogRequest.SerializeToString,
                response_deserializer=device__pb2.DriverLogResponse.FromString,
                _registered_method=True)
        self.ScreenSnapshot = channel.unary_unary(
                '/tap.v1.DeviceService/ScreenSnapshot',
                request_serializer=device__pb2.ScreenSnapshotRequest.SerializeToString,
                response_deserializer=device__pb2.ScreenSnapshotResponse.FromString,
                _registered_method=True)
        self.ResolveRef = channel.unary_unary(
                '/tap.v1.DeviceService/ResolveRef',
                request_serializer=device__pb2.ResolveRefRequest.SerializeToString,
                response_deserializer=device__pb2.ResolveRefResponse.FromString,
                _registered_method=True)


class DeviceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attach(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detach(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Screenshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DriverLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScreenSnapshot(self, request, context):
        """A compact, ref-addressed outline of the screen, parsed from the diagnostic hierarchy dump
        (`.docs/agent-surface.md`). Refs name selectors the daemon synthesised, never node handles.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveRef(self, request, context):
        """The selector a ref of the latest snapshot names. Unknown ref: NOT_FOUND (UNKNOWN_REF);
        a node with no selector: FAILED_PRECONDITION (REF_NOT_ADDRESSABLE).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=device__pb2.ListDevicesRequest.FromString,
                    response_serializer=device__pb2.ListDevicesResponse.SerializeToString,
            ),
            'Attach': grpc.unary_unary_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=device__pb2.AttachRequest.FromString,
                    response_serializer=device__pb2.AttachResponse.SerializeToString,
            ),
            'Detach': grpc.unary_unary_rpc_method_handler(
                    servicer.Detach,
                    request_deserializer=device__pb2.DetachRequest.FromString,
                    response_serializer=device__pb2.DetachResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=device__pb2.ExecuteRequest.FromString,
                    response_serializer=device__pb2.ExecuteResponse.SerializeToString,
            ),
            'Screenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Screenshot,
                    request_deserializer=device__pb2.ScreenshotRequest.FromString,
                    response_serializer=device__pb2.ScreenshotResponse.SerializeToString,
            ),
            'DriverLog': grpc.unary_unary_rpc_method_handler(
                    servicer.DriverLog,
                    request_deserializer=device__pb2.DriverLogRequest.FromString,
                    response_serializer=device__pb2.DriverLogResponse.SerializeToString,
            ),
            'ScreenSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ScreenSnapshot,
                    request_deserializer=device__pb2.ScreenSnapshotRequest.FromString,
                    response_serializer=device__pb2.ScreenSnapshotResponse.SerializeToString,
            ),
            'ResolveRef': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveRef,
                    request_deserializer=device__pb2.ResolveRefRequest.FromString,
                    response_serializer=device__pb2.ResolveRefResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tap.v1.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tap.v1.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/ListDevices',
            device__pb2.ListDevicesRequest.SerializeToString,
            device__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/Attach',
            device__pb2.AttachRequest.SerializeToString,
            device__pb2.AttachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Detach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/Detach',
            device__pb2.DetachRequest.SerializeToString,
            device__pb2.DetachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/Execute',
            device__pb2.ExecuteRequest.SerializeToString,
            device__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Screenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/Screenshot',
            device__pb2.ScreenshotRequest.SerializeToString,
            device__pb2.ScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DriverLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/DriverLog',
            device__pb2.DriverLogRequest.SerializeToString,
            device__pb2.DriverLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScreenSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/ScreenSnapshot',
            device__pb2.ScreenSnapshotRequest.SerializeToString,
            device__pb2.ScreenSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveRef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.DeviceService/ResolveRef',
            device__pb2.ResolveRefRequest.SerializeToString,
            device__pb2.ResolveRefResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
