# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: failure.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'failure.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import command_pb2 as command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfailure.proto\x12\x06tap.v1\x1a\rcommand.proto\"\x8a\x01\n\x07\x46\x61ilure\x12%\n\x06reason\x18\x01 \x01(\x0e\x32\x15.tap.v1.FailureReason\x12\x0e\n\x06serial\x18\x02 \x01(\t\x12\x11\n\twaited_ms\x18\x03 \x01(\x03\x12%\n\nerror_code\x18\x04 \x01(\x0e\x32\x11.tap.v1.ErrorCode\x12\x0e\n\x06\x64\x65tail\x18\x05 \x01(\t*\xf8\x06\n\rFailureReason\x12\x1e\n\x1a\x46\x41ILURE_REASON_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x46\x41ILURE_REASON_INTERNAL\x10\x01\x12#\n\x1f\x46\x41ILURE_REASON_INVALID_ARGUMENT\x10\x02\x12\"\n\x1e\x46\x41ILURE_REASON_UNAUTHENTICATED\x10\x03\x12,\n(FAILURE_REASON_UNKNOWN_CLIENT_CONNECTION\x10\x04\x12*\n&FAILURE_REASON_UNKNOWN_ATTACHED_DEVICE\x10\x05\x12\x1c\n\x18\x46\x41ILURE_REASON_NOT_OWNER\x10\x06\x12\x1e\n\x1a\x46\x41ILURE_REASON_DEVICE_BUSY\x10\x07\x12%\n!FAILURE_REASON_DEVICE_QUARANTINED\x10\x08\x12$\n FAILURE_REASON_HOST_WAIT_TIMEOUT\x10\t\x12\x1e\n\x1a\x46\x41ILURE_REASON_ADB_TIMEOUT\x10\n\x12\x1d\n\x19\x46\x41ILURE_REASON_ADB_FAILED\x10\x0b\x12%\n!FAILURE_REASON_ADB_REAP_UNCERTAIN\x10\x0c\x12 \n\x1c\x46\x41ILURE_REASON_APP_LIFECYCLE\x10\r\x12(\n$FAILURE_REASON_DRIVER_BUILD_MISMATCH\x10\x0e\x12&\n\"FAILURE_REASON_DRIVER_START_FAILED\x10\x0f\x12#\n\x1f\x46\x41ILURE_REASON_DRIVER_TRANSPORT\x10\x10\x12!\n\x1d\x46\x41ILURE_REASON_DRIVER_COMMAND\x10\x11\x12#\n\x1f\x46\x41ILURE_REASON_SESSION_UNUSABLE\x10\x12\x12&\n\"FAILURE_REASON_DAEMON_PRECONDITION\x10\x13\x12\x1e\n\x1a\x46\x41ILURE_REASON_UNKNOWN_REF\x10\x14\x12&\n\"FAILURE_REASON_REF_NOT_ADDRESSABLE\x10\x15\x12\"\n\x1e\x46\x41ILURE_REASON_UNSUPPORTED_API\x10\x16\x12!\n\x1d\x46\x41ILURE_REASON_DEVICE_SETTING\x10\x17\x42\x32\n io.github.noamcohen48.tap.api.v1B\x0c\x46\x61ilureProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'failure_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n io.github.noamcohen48.tap.api.v1B\014FailureProtoP\001'
  _globals['_FAILUREREASON']._serialized_start=182
  _globals['_FAILUREREASON']._serialized_end=1070
  _globals['_FAILURE']._serialized_start=41
  _globals['_FAILURE']._serialized_end=179
# @@protoc_insertion_point(module_scope)
