# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import video_pb2 as video__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in video_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchVideo = channel.unary_stream(
                '/tap.v1.VideoService/WatchVideo',
                request_serializer=video__pb2.WatchVideoRequest.SerializeToString,
                response_deserializer=video__pb2.WatchVideoResponse.FromString,
                _registered_method=True)


class VideoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def WatchVideo(self, request, context):
        """One producer per serial, shared by readers. Cancellation releases only this reader.
        Optional: requires the pinned scrcpy 4.1 server on the host. No input or screen wake.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WatchVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchVideo,
                    request_deserializer=video__pb2.WatchVideoRequest.FromString,
                    response_serializer=video__pb2.WatchVideoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tap.v1.VideoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tap.v1.VideoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WatchVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tap.v1.VideoService/WatchVideo',
            video__pb2.WatchVideoRequest.SerializeToString,
            video__pb2.WatchVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
