# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x06tap.v1\"#\n\x11WatchVideoRequest\x12\x0e\n\x06serial\x18\x01 \x01(\t\"h\n\x0bVideoHeader\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x10\n\x08\x63lock_id\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x15\n\rconfiguration\x18\x05 \x01(\x0c\"\x84\x01\n\nVideoFrame\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x0e\n\x06pts_us\x18\x02 \x01(\x03\x12\x11\n\tkey_frame\x18\x03 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x1d\n\x15received_monotonic_ns\x18\x05 \x01(\x03\x12\x19\n\x11received_epoch_ms\x18\x06 \x01(\x03\"j\n\x12WatchVideoResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x13.tap.v1.VideoHeaderH\x00\x12#\n\x05\x66rame\x18\x02 \x01(\x0b\x32\x12.tap.v1.VideoFrameH\x00\x42\x08\n\x06update2U\n\x0cVideoService\x12\x45\n\nWatchVideo\x12\x19.tap.v1.WatchVideoRequest\x1a\x1a.tap.v1.WatchVideoResponse0\x01\x42$\n io.github.noamcohen48.tap.api.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n io.github.noamcohen48.tap.api.v1P\001'
  _globals['_WATCHVIDEOREQUEST']._serialized_start=23
  _globals['_WATCHVIDEOREQUEST']._serialized_end=58
  _globals['_VIDEOHEADER']._serialized_start=60
  _globals['_VIDEOHEADER']._serialized_end=164
  _globals['_VIDEOFRAME']._serialized_start=167
  _globals['_VIDEOFRAME']._serialized_end=299
  _globals['_WATCHVIDEORESPONSE']._serialized_start=301
  _globals['_WATCHVIDEORESPONSE']._serialized_end=407
  _globals['_VIDEOSERVICE']._serialized_start=409
  _globals['_VIDEOSERVICE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
