# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import watch_pb2 as watch__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in watch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WatchServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Watch = channel.unary_stream(
                '/tap.v1.WatchService/Watch',
                request_serializer=watch__pb2.WatchRequest.SerializeToString,
                response_deserializer=watch__pb2.WatchResponse.FromString,
                _registered_method=True)
        self.WatchVideo = channel.unary_stream(
                '/tap.v1.WatchService/WatchVideo',
                request_serializer=watch__pb2.WatchVideoRequest.SerializeToString,
                response_deserializer=watch__pb2.WatchVideoResponse.FromString,
                _registered_method=True)


class WatchServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Watch(self, request, context):
        """The daemon-wide activity log after `after_seq`: the retained backlog, then live activity
        as it happens, until the client cancels or the daemon stops. The first response also
        carries the live connections, so names survive eviction of their `connection_opened`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchVideo(self, request, context):
        """One device's screen as H.264, from a scrcpy server the daemon runs while anyone watches
        that serial; readers of one serial share it. Needs `tap start --scrcpy-server`. No input,
        no screen wake, no attachment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=watch__pb2.WatchRequest.FromString,
                    response_serializer=watch__pb2.WatchResponse.SerializeToString,
            ),
            'WatchVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchVideo,
                    request_deserializer=watch__pb2.WatchVideoRequest.FromString,
                    response_serializer=watch__pb2.WatchVideoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tap.v1.WatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tap.v1.WatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WatchService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tap.v1.WatchService/Watch',
            watch__pb2.WatchRequest.SerializeToString,
            watch__pb2.WatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tap.v1.WatchService/WatchVideo',
            watch__pb2.WatchVideoRequest.SerializeToString,
            watch__pb2.WatchVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
