"""Tap Python client: drives Android devices through the Tap host server.

from tap_e2e import TapClient, text, res

with TapClient.create() as client, client.connect("smoke") as connection:  # `tap start` first
    with connection.attach_device("emulator-5554") as device:
        app = device.app("com.example.app")
        app.cold_launch()
        app.element(res("login")).tap()
        app.wait(text("Welcome")).visible()
"""
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _dist_version

from .app import App
from .device import KEYCODE_BACK, KEYCODE_HOME, Device, Timeouts
from .element import DOWN, LEFT, RIGHT, UP, Element, ElementWait
from .screen import Screen
from .errors import (
    AppLifecycleError,
    CommandError,
    DeviceBusyError,
    DeviceQuarantinedError,
    ServerError,
    TapError,
    WaitTimeoutError,
)
from .models import (
    AppProcess,
    Artifact,
    AttachedDeviceEntry,
    Bounds,
    Capture,
    ConnectionEntry,
    DeviceEntry,
    DeviceInfo,
    DeviceState,
    Direction,
    DriverLog,
    ElementSnapshot,
    ErrorCode,
    EventLog,
    FailureReason,
    Hierarchy,
    ImageFormat,
    LoggedEvent,
    MatchMode,
    NodeChange,
    NodeFlag,
    Recording,
    ScreenNode,
    ScreenSnapshot,
    Screenshot,
    SelectorCandidate,
    SelectorKind,
    ServerDefaults,
    ServerInfo,
    StabilitySignal,
    WaitReason,
)
from .selectors import (
    CONTAINS,
    ENDS_WITH,
    EXACT,
    REGEX,
    STARTS_WITH,
    Selector,
    all_of,
    any_of,
    class_name,
    clickable,
    desc,
    hint,
    res,
    res_id,
    scrollable,
    text,
    text_contains,
    text_matches,
    text_starts_with,
)
from .client import (
    DaemonStartResult,
    Endpoint,
    TapClient,
    TapConnection,
    resolve_address,
    running_server,
    start_daemon,
    stop_daemon,
)

__all__ = [
    "CONTAINS",
    "DOWN",
    "ENDS_WITH",
    "EXACT",
    "KEYCODE_BACK",
    "KEYCODE_HOME",
    "LEFT",
    "REGEX",
    "RIGHT",
    "STARTS_WITH",
    "UP",
    "App",
    "AppLifecycleError",
    "AppProcess",
    "Artifact",
    "AttachedDeviceEntry",
    "Bounds",
    "CommandError",
    "ConnectionEntry",
    "DaemonStartResult",
    "Device",
    "DeviceBusyError",
    "DeviceEntry",
    "DeviceInfo",
    "DeviceQuarantinedError",
    "DeviceState",
    "Direction",
    "Capture",
    "DriverLog",
    "Element",
    "ElementSnapshot",
    "ElementWait",
    "Endpoint",
    "ErrorCode",
    "EventLog",
    "FailureReason",
    "Hierarchy",
    "ImageFormat",
    "LoggedEvent",
    "MatchMode",
    "NodeChange",
    "NodeFlag",
    "Recording",
    "Screen",
    "ScreenNode",
    "ScreenSnapshot",
    "Screenshot",
    "Selector",
    "SelectorCandidate",
    "SelectorKind",
    "ServerDefaults",
    "ServerError",
    "ServerInfo",
    "StabilitySignal",
    "TapClient",
    "TapConnection",
    "TapError",
    "Timeouts",
    "WaitReason",
    "WaitTimeoutError",
    "all_of",
    "any_of",
    "class_name",
    "clickable",
    "desc",
    "hint",
    "res",
    "res_id",
    "resolve_address",
    "running_server",
    "scrollable",
    "start_daemon",
    "stop_daemon",
    "text",
    "text_contains",
    "text_matches",
    "text_starts_with",
]

try:
    __version__ = _dist_version("tap-e2e")
except PackageNotFoundError:  # running from a checkout without an install
    __version__ = "0.0.0+unknown"
