#!/usr/bin/env bash
# Builds the public documentation twice from the same sources:
#
#   build/site/            the website (MkDocs Material), for hosting
#   build/docs-md/         the same guide plus every reference as plain Markdown (Kotlin, Python,
#   build/tap-docs-md.zip  gRPC, tap-agent) and the changelog, for reading in a repo or offline;
#                          zipped for the CI artifact, and attached to every GitHub Release
#
# The site also carries the Markdown, for LLMs and agents (scripts/llms_txt.py): every page's
# .md next to its HTML, llms.txt, llms-full.txt and tap-docs-md.zip.
#
# Generated inputs (all ignored by git, regenerated on every run):
#   docs/reference/kotlin-api/     Dokka HTML aggregate of :clients:kotlin:sdk + :junit5 (site)
#   build/docs-md/reference/kotlin/ Dokka GFM of the same modules (-Ptap.dokkaFormat=gfm)
#   docs/reference/grpc.md         protoc-gen-doc Markdown for contracts/proto/*.proto (both)
#   (Python, site)                 mkdocstrings renders clients/python/tap_e2e at mkdocs time
#   build/docs-md/reference/python/ the same pages with lazydocs Markdown (scripts/python_ref_md.py)
#   docs/agent/commands.md         tap-agent command reference (clients/agent/scripts/gen_reference.py)
#
# Requirements: a local JDK 17 (Gradle's daemon JVM), `buf` and `protoc-gen-doc` on PATH (or set BUF /
# PROTOC_GEN_DOC), and a Python with `pip install -r docs/requirements.txt -e "clients/python[dev]"
# -e clients/agent` (mkdocs, mkdocstrings, lazydocs; the client with its dev extra so
# `tap_e2e.pytest_plugin` imports; tap-agent for its command reference).
set -euo pipefail
cd "$(dirname "$0")/.."

BUF=${BUF:-buf}
PROTOC_GEN_DOC=${PROTOC_GEN_DOC:-$(command -v protoc-gen-doc || true)}
MKDOCS=${MKDOCS:-mkdocs}
PYTHON=${PYTHON:-python}
MD=build/docs-md

echo "== Kotlin reference (Dokka HTML for the site, GFM for the Markdown bundle)"
./gradlew --quiet :dokkaGenerate
rm -rf docs/reference/kotlin docs/reference/kotlin-api
cp -r build/dokka/html docs/reference/kotlin-api
./gradlew --quiet -Ptap.dokkaFormat=gfm \
  :clients:kotlin:sdk:dokkaGeneratePublicationHtml :clients:kotlin:junit5:dokkaGeneratePublicationHtml
rm -rf "$MD" && mkdir -p "$MD/reference/kotlin"
cp -r clients/kotlin/sdk/build/dokka/gfm "$MD/reference/kotlin/tap-client"
cp -r clients/kotlin/junit5/build/dokka/gfm "$MD/reference/kotlin/tap-junit5"

echo "== gRPC reference (protoc-gen-doc)"
[ -n "$PROTOC_GEN_DOC" ] || { echo "protoc-gen-doc not found; set PROTOC_GEN_DOC" >&2; exit 1; }
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
cat > "$tmp/buf.gen.yaml" <<YAML
version: v2
plugins:
  - local: $PROTOC_GEN_DOC
    out: $tmp/out
    opt: markdown,grpc.md
YAML
"$BUF" generate --template "$tmp/buf.gen.yaml" contracts/proto --exclude-path contracts/proto/wire
{
  echo "# gRPC server API (tap.v1)"
  echo
  echo "Generated from \`contracts/proto/*.proto\` by protoc-gen-doc. The narrative"
  echo "contract — run liveness, the pool, sessions, status mapping — is in the repository's"
  echo "\`.docs/server-api.md\`."
  echo
  # protoc-gen-doc emits its own H1 and a long TOC; keep the body from the file heading on
  # (mkdocs renders its own TOC from the headings).
  sed -n '/^<a name="[a-z]*-proto"><\/a>/,$p' "$tmp/out/grpc.md" | grep -v '^<p align="right">'
} > docs/reference/grpc.md

echo "== tap-agent command reference"
"$PYTHON" clients/agent/scripts/gen_reference.py docs/agent/commands.md

echo "== Site (mkdocs)"
"$MKDOCS" build --strict

echo "== Markdown bundle"
# The guide and the hand-written reference pages are Markdown already. The Kotlin page (a link to
# the Dokka HTML) becomes an index of the GFM output; the Python pages' mkdocstrings directives
# are replaced by lazydocs Markdown of the same objects (scripts/python_ref_md.py).
(cd docs && find . -name '*.md' -not -path './reference/kotlin-api/*' -not -path './assets/dokka/*' -exec cp --parents {} "../$MD/" \;)
cat > "$MD/reference/kotlin.md" <<'MDX'
# Kotlin client

Generated by Dokka (GFM) from the KDoc of the two modules:

- [`tap-client`](kotlin/tap-client/index.md) — `io.github.noamcohen48.tap.sdk`: `TapClient`, `TapConnection`, `Device`,
  `Element`, `ElementWait`, `App`, the selector DSL, models, exceptions
- [`tap-junit5`](kotlin/tap-junit5/index.md) — `io.github.noamcohen48.tap.junit5`: `@TapTest`, `@TapDevice`,
  `@TapDevices`, `Devices`, `TapConfig`
MDX
"$PYTHON" scripts/python_ref_md.py "$MD/reference/python"
mkdir -p "$MD/agent"
cp clients/agent/README.md "$MD/agent/README.md"
cp clients/agent/tap_agent/SKILL.md "$MD/agent/SKILL.md"
cp CHANGELOG.md "$MD/CHANGELOG.md"
mv "$MD/index.md" "$MD/README.md"
rm -f build/tap-docs-md.zip
python3 -c "import shutil; shutil.make_archive('build/tap-docs-md', 'zip', 'build', 'docs-md')"

echo "== Markdown in the site (llms.txt)"
"$PYTHON" scripts/llms_txt.py "$MD" build/site
echo "built build/site, build/docs-md and build/tap-docs-md.zip"
