#!/usr/bin/env bash
# Builds the public documentation twice from the same sources:
#
#   build/site/            the website (MkDocs Material), for hosting
#   build/docs-md/         the same guide plus every reference as plain Markdown, for reading
#   build/tap-docs-md.zip  in a repo or offline; zipped for the CI artifact
#
# Generated inputs (all ignored by git, regenerated on every run):
#   docs/reference/kotlin/         Dokka HTML aggregate of :clients:kotlin:sdk + :junit5 (site)
#   build/docs-md/reference/kotlin/ Dokka GFM of the same modules (-Ptap.dokkaFormat=gfm)
#   docs/reference/grpc.md         protoc-gen-doc Markdown for contracts/api/proto/tap.proto (both)
#   (Python, site)                 mkdocstrings renders clients/python/tap at mkdocs time
#   build/docs-md/reference/python/ lazydocs Markdown of the same modules
#
# Requirements: JDK 17 on JAVA_HOME (Gradle), `buf` and `protoc-gen-doc` on PATH (or set BUF /
# PROTOC_GEN_DOC), and a Python with `pip install -r docs/requirements.txt -e "clients/python[dev]"`
# (mkdocs, mkdocstrings, lazydocs; the client with its dev extra so `tap.pytest_plugin` imports).
set -euo pipefail
cd "$(dirname "$0")/.."

BUF=${BUF:-buf}
PROTOC_GEN_DOC=${PROTOC_GEN_DOC:-$(command -v protoc-gen-doc || true)}
MKDOCS=${MKDOCS:-mkdocs}
LAZYDOCS=${LAZYDOCS:-lazydocs}
MD=build/docs-md

echo "== Kotlin reference (Dokka HTML for the site, GFM for the Markdown bundle)"
./gradlew --quiet :dokkaGenerate
rm -rf docs/reference/kotlin
cp -r build/dokka/html docs/reference/kotlin
./gradlew --quiet -Ptap.dokkaFormat=gfm \
  :clients:kotlin:sdk:dokkaGeneratePublicationHtml :clients:kotlin:junit5:dokkaGeneratePublicationHtml
rm -rf "$MD" && mkdir -p "$MD/reference/kotlin" "$MD/reference/python"
cp -r clients/kotlin/sdk/build/dokka/gfm "$MD/reference/kotlin/tap-client"
cp -r clients/kotlin/junit5/build/dokka/gfm "$MD/reference/kotlin/tap-junit5"

echo "== Python reference for the Markdown bundle (lazydocs)"
lazy_log=$("$LAZYDOCS" tap.device tap.element tap.selectors tap.app tap.service tap.errors tap.pytest_plugin \
  --output-path "$MD/reference/python" --overview-file index.md --no-watermark \
  --src-base-url https://github.com/NoamCohen48/tap/blob/main/ 2>&1) || { echo "$lazy_log" >&2; exit 1; }
rm -f "$MD/reference/python/.pages"

echo "== gRPC reference (protoc-gen-doc)"
[ -n "$PROTOC_GEN_DOC" ] || { echo "protoc-gen-doc not found; set PROTOC_GEN_DOC" >&2; exit 1; }
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
cat > "$tmp/buf.gen.yaml" <<YAML
version: v2
plugins:
  - local: $PROTOC_GEN_DOC
    out: $tmp/out
    opt: markdown,grpc.md
YAML
"$BUF" generate --template "$tmp/buf.gen.yaml" contracts/api
{
  echo "# gRPC service API (tap.v1)"
  echo
  echo "Generated from \`contracts/api/proto/tap.proto\` by protoc-gen-doc. The narrative"
  echo "contract — run liveness, the pool, sessions, status mapping — is in the repository's"
  echo "\`.docs/service-api.md\`."
  echo
  # protoc-gen-doc emits its own H1 and a long TOC; keep the body from the file heading on
  # (mkdocs renders its own TOC from the headings).
  sed -n '/^<a name="tap-proto"><\/a>/,$p' "$tmp/out/grpc.md" | grep -v '^<p align="right">'
} > docs/reference/grpc.md

echo "== Site (mkdocs)"
"$MKDOCS" build --strict

echo "== Markdown bundle"
# The guide and the hand-written reference pages are Markdown already; only the two pages that
# embed site-specific machinery (the Dokka HTML link, the mkdocstrings directives) are replaced
# with plain indexes of the generated Markdown.
(cd docs && find . -name '*.md' -not -path './reference/kotlin/*' -exec cp --parents {} "../$MD/" \;)
cat > "$MD/reference/kotlin.md" <<'MDX'
# Kotlin client

Generated by Dokka (GFM) from the KDoc of the two modules:

- [`tap-client`](kotlin/tap-client/index.md) — `com.company.tap.sdk`: `TapClient`, `Connection`, `Device`,
  `Element`, `ElementWait`, `App`, the selector DSL, exceptions
- [`tap-junit5`](kotlin/tap-junit5/index.md) — `com.company.tap.junit5`: `@TapTest`, `@TapDevice`,
  `@TapDevices`, `Devices`, `TapConfig`
MDX
cat > "$MD/reference/python.md" <<'MDX'
# Python client

Package `tap-e2e`, importable as `tap`. Generated by lazydocs from the docstrings:

- [API overview](python/index.md)
- [`tap.device`](python/tap.device.md) · [`tap.element`](python/tap.element.md) ·
  [`tap.selectors`](python/tap.selectors.md) · [`tap.app`](python/tap.app.md) ·
  [`tap.service`](python/tap.service.md) · [`tap.errors`](python/tap.errors.md) ·
  [`tap.pytest_plugin`](python/tap.pytest_plugin.md)
MDX
mv "$MD/index.md" "$MD/README.md"
rm -f build/tap-docs-md.zip
python3 -c "import shutil; shutil.make_archive('build/tap-docs-md', 'zip', 'build', 'docs-md')"
echo "built build/site, build/docs-md and build/tap-docs-md.zip"
