#!/usr/bin/env bash
# Builds the public documentation twice from the same sources:
#
#   build/site/            the website (MkDocs Material), for hosting
#   build/docs-md/         the same guide plus every reference as plain Markdown (Kotlin, Python,
#   build/tap-docs-md.zip  gRPC, tap-agent) and the changelog, for reading in a repo or offline;
#                          zipped for the CI artifact, and attached to every GitHub Release
#
# Generated inputs (all ignored by git, regenerated on every run):
#   docs/reference/kotlin-api/     Dokka HTML aggregate of :clients:kotlin:sdk + :junit5 (site)
#   build/docs-md/reference/kotlin/ Dokka GFM of the same modules (-Ptap.dokkaFormat=gfm)
#   docs/reference/grpc.md         protoc-gen-doc Markdown for contracts/proto/*.proto (both)
#   (Python, site)                 mkdocstrings renders clients/python/tap_e2e at mkdocs time
#   build/docs-md/reference/python/ lazydocs Markdown of the same modules
#
# Requirements: a local JDK 17 (Gradle's daemon JVM), `buf` and `protoc-gen-doc` on PATH (or set BUF /
# PROTOC_GEN_DOC), and a Python with `pip install -r docs/requirements.txt -e "clients/python[dev]"`
# (mkdocs, mkdocstrings, lazydocs; the client with its dev extra so `tap_e2e.pytest_plugin` imports).
set -euo pipefail
cd "$(dirname "$0")/.."

BUF=${BUF:-buf}
PROTOC_GEN_DOC=${PROTOC_GEN_DOC:-$(command -v protoc-gen-doc || true)}
MKDOCS=${MKDOCS:-mkdocs}
LAZYDOCS=${LAZYDOCS:-lazydocs}
MD=build/docs-md

echo "== Kotlin reference (Dokka HTML for the site, GFM for the Markdown bundle)"
./gradlew --quiet :dokkaGenerate
rm -rf docs/reference/kotlin docs/reference/kotlin-api
cp -r build/dokka/html docs/reference/kotlin-api
./gradlew --quiet -Ptap.dokkaFormat=gfm \
  :clients:kotlin:sdk:dokkaGeneratePublicationHtml :clients:kotlin:junit5:dokkaGeneratePublicationHtml
rm -rf "$MD" && mkdir -p "$MD/reference/kotlin" "$MD/reference/python"
cp -r clients/kotlin/sdk/build/dokka/gfm "$MD/reference/kotlin/tap-client"
cp -r clients/kotlin/junit5/build/dokka/gfm "$MD/reference/kotlin/tap-junit5"

echo "== Python reference for the Markdown bundle (lazydocs)"
lazy_log=$("$LAZYDOCS" tap_e2e.device tap_e2e.element tap_e2e.selectors tap_e2e.app tap_e2e.screen tap_e2e.client tap_e2e.models tap_e2e.errors tap_e2e.pytest_plugin \
  --output-path "$MD/reference/python" --overview-file index.md --no-watermark \
  --src-base-url https://github.com/NoamCohen48/tap/blob/main/ 2>&1) || { echo "$lazy_log" >&2; exit 1; }
rm -f "$MD/reference/python/.pages"

echo "== gRPC reference (protoc-gen-doc)"
[ -n "$PROTOC_GEN_DOC" ] || { echo "protoc-gen-doc not found; set PROTOC_GEN_DOC" >&2; exit 1; }
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
cat > "$tmp/buf.gen.yaml" <<YAML
version: v2
plugins:
  - local: $PROTOC_GEN_DOC
    out: $tmp/out
    opt: markdown,grpc.md
YAML
"$BUF" generate --template "$tmp/buf.gen.yaml" contracts/proto --exclude-path contracts/proto/wire
{
  echo "# gRPC server API (tap.v1)"
  echo
  echo "Generated from \`contracts/proto/*.proto\` by protoc-gen-doc. The narrative"
  echo "contract — run liveness, the pool, sessions, status mapping — is in the repository's"
  echo "\`.docs/server-api.md\`."
  echo
  # protoc-gen-doc emits its own H1 and a long TOC; keep the body from the file heading on
  # (mkdocs renders its own TOC from the headings).
  sed -n '/^<a name="[a-z]*-proto"><\/a>/,$p' "$tmp/out/grpc.md" | grep -v '^<p align="right">'
} > docs/reference/grpc.md

echo "== Site (mkdocs)"
"$MKDOCS" build --strict

echo "== Markdown bundle"
# The guide and the hand-written reference pages are Markdown already; only the two pages that
# embed site-specific machinery (the Dokka HTML link, the mkdocstrings directives) are replaced
# with plain indexes of the generated Markdown.
(cd docs && find . -name '*.md' -not -path './reference/kotlin-api/*' -not -path './assets/dokka/*' -exec cp --parents {} "../$MD/" \;)
cat > "$MD/reference/kotlin.md" <<'MDX'
# Kotlin client

Generated by Dokka (GFM) from the KDoc of the two modules:

- [`tap-client`](kotlin/tap-client/index.md) — `io.github.noamcohen48.tap.sdk`: `TapClient`, `TapConnection`, `Device`,
  `Element`, `ElementWait`, `App`, the selector DSL, models, exceptions
- [`tap-junit5`](kotlin/tap-junit5/index.md) — `io.github.noamcohen48.tap.junit5`: `@TapTest`, `@TapDevice`,
  `@TapDevices`, `Devices`, `TapConfig`
MDX
cat > "$MD/reference/python.md" <<'MDX'
# Python client

Package `tap-e2e`, imported as `tap_e2e`. Generated by lazydocs from the docstrings:

- [API overview](python/index.md)
- [`tap_e2e.device`](python/tap_e2e.device.md) · [`tap_e2e.element`](python/tap_e2e.element.md) ·
  [`tap_e2e.selectors`](python/tap_e2e.selectors.md) · [`tap_e2e.app`](python/tap_e2e.app.md) ·
  [`tap_e2e.client`](python/tap_e2e.client.md) · [`tap_e2e.models`](python/tap_e2e.models.md) ·
  [`tap_e2e.errors`](python/tap_e2e.errors.md) ·
  [`tap_e2e.pytest_plugin`](python/tap_e2e.pytest_plugin.md)
MDX
mkdir -p "$MD/reference/agent"
cp clients/agent/README.md "$MD/reference/agent/README.md"
cp clients/agent/tap_agent/SKILL.md "$MD/reference/agent/SKILL.md"
cat > "$MD/reference/agent.md" <<'MDX'
# tap-agent (experimental)

Package `tap-agent`: the CLI and MCP server for coding agents. The guide page is
[Coding agents](../guide/agents.md); `tap-agent --help` lists every verb.

- [README](agent/README.md) — install, sessions, export, MCP setup
- [SKILL.md](agent/SKILL.md) — the instructions `tap-agent skill` gives an agent
MDX
cp CHANGELOG.md "$MD/CHANGELOG.md"
mv "$MD/index.md" "$MD/README.md"
rm -f build/tap-docs-md.zip
python3 -c "import shutil; shutil.make_archive('build/tap-docs-md', 'zip', 'build', 'docs-md')"
echo "built build/site, build/docs-md and build/tap-docs-md.zip"
