# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import app_pb2 as app__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AppServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Install = channel.unary_unary(
                '/tap.v1.AppService/Install',
                request_serializer=app__pb2.AppInstallRequest.SerializeToString,
                response_deserializer=app__pb2.AppEmpty.FromString,
                _registered_method=True)
        self.Uninstall = channel.unary_unary(
                '/tap.v1.AppService/Uninstall',
                request_serializer=app__pb2.AppRequest.SerializeToString,
                response_deserializer=app__pb2.AppEmpty.FromString,
                _registered_method=True)
        self.IsInstalled = channel.unary_unary(
                '/tap.v1.AppService/IsInstalled',
                request_serializer=app__pb2.AppRequest.SerializeToString,
                response_deserializer=app__pb2.AppBool.FromString,
                _registered_method=True)
        self.ForceStop = channel.unary_unary(
                '/tap.v1.AppService/ForceStop',
                request_serializer=app__pb2.AppRequest.SerializeToString,
                response_deserializer=app__pb2.AppEmpty.FromString,
                _registered_method=True)
        self.ClearData = channel.unary_unary(
                '/tap.v1.AppService/ClearData',
                request_serializer=app__pb2.AppRequest.SerializeToString,
                response_deserializer=app__pb2.AppEmpty.FromString,
                _registered_method=True)
        self.GrantPermission = channel.unary_unary(
                '/tap.v1.AppService/GrantPermission',
                request_serializer=app__pb2.AppGrantRequest.SerializeToString,
                response_deserializer=app__pb2.AppEmpty.FromString,
                _registered_method=True)
        self.Launch = channel.unary_unary(
                '/tap.v1.AppService/Launch',
                request_serializer=app__pb2.AppLaunchRequest.SerializeToString,
                response_deserializer=app__pb2.AppEmpty.FromString,
                _registered_method=True)
        self.ColdLaunch = channel.unary_unary(
                '/tap.v1.AppService/ColdLaunch',
                request_serializer=app__pb2.AppLaunchRequest.SerializeToString,
                response_deserializer=app__pb2.ProcessIdentity.FromString,
                _registered_method=True)
        self.Process = channel.unary_unary(
                '/tap.v1.AppService/Process',
                request_serializer=app__pb2.AppRequest.SerializeToString,
                response_deserializer=app__pb2.ProcessIdentity.FromString,
                _registered_method=True)
        self.IsRunning = channel.unary_unary(
                '/tap.v1.AppService/IsRunning',
                request_serializer=app__pb2.AppRequest.SerializeToString,
                response_deserializer=app__pb2.AppBool.FromString,
                _registered_method=True)
        self.AwaitIdle = channel.unary_unary(
                '/tap.v1.AppService/AwaitIdle',
                request_serializer=app__pb2.AppAwaitIdleRequest.SerializeToString,
                response_deserializer=app__pb2.AppEmpty.FromString,
                _registered_method=True)


class AppServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Install(self, request, context):
        """`adb install -r -t`, verified.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Uninstall(self, request, context):
        """`pm uninstall`, verified.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsInstalled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceStop(self, request, context):
        """`am force-stop` plus proof that no process remains.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearData(self, request, context):
        """`pm clear`; data, cache and runtime permissions gone, app left stopped.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantPermission(self, request, context):
        """`pm grant` a runtime permission.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Launch(self, request, context):
        """Start the activity (or the launcher) and wait for the package to own the focused window.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ColdLaunch(self, request, context):
        """Verified force-stop, launch, then a new process identity in the foreground.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Process(self, request, context):
        """The single current process identity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsRunning(self, request, context):
        """Whether any process of the package is alive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AwaitIdle(self, request, context):
        """Wait until the app's sync-sdk busy count is zero and stable for `stable_for_ms`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Install': grpc.unary_unary_rpc_method_handler(
                    servicer.Install,
                    request_deserializer=app__pb2.AppInstallRequest.FromString,
                    response_serializer=app__pb2.AppEmpty.SerializeToString,
            ),
            'Uninstall': grpc.unary_unary_rpc_method_handler(
                    servicer.Uninstall,
                    request_deserializer=app__pb2.AppRequest.FromString,
                    response_serializer=app__pb2.AppEmpty.SerializeToString,
            ),
            'IsInstalled': grpc.unary_unary_rpc_method_handler(
                    servicer.IsInstalled,
                    request_deserializer=app__pb2.AppRequest.FromString,
                    response_serializer=app__pb2.AppBool.SerializeToString,
            ),
            'ForceStop': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceStop,
                    request_deserializer=app__pb2.AppRequest.FromString,
                    response_serializer=app__pb2.AppEmpty.SerializeToString,
            ),
            'ClearData': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearData,
                    request_deserializer=app__pb2.AppRequest.FromString,
                    response_serializer=app__pb2.AppEmpty.SerializeToString,
            ),
            'GrantPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantPermission,
                    request_deserializer=app__pb2.AppGrantRequest.FromString,
                    response_serializer=app__pb2.AppEmpty.SerializeToString,
            ),
            'Launch': grpc.unary_unary_rpc_method_handler(
                    servicer.Launch,
                    request_deserializer=app__pb2.AppLaunchRequest.FromString,
                    response_serializer=app__pb2.AppEmpty.SerializeToString,
            ),
            'ColdLaunch': grpc.unary_unary_rpc_method_handler(
                    servicer.ColdLaunch,
                    request_deserializer=app__pb2.AppLaunchRequest.FromString,
                    response_serializer=app__pb2.ProcessIdentity.SerializeToString,
            ),
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=app__pb2.AppRequest.FromString,
                    response_serializer=app__pb2.ProcessIdentity.SerializeToString,
            ),
            'IsRunning': grpc.unary_unary_rpc_method_handler(
                    servicer.IsRunning,
                    request_deserializer=app__pb2.AppRequest.FromString,
                    response_serializer=app__pb2.AppBool.SerializeToString,
            ),
            'AwaitIdle': grpc.unary_unary_rpc_method_handler(
                    servicer.AwaitIdle,
                    request_deserializer=app__pb2.AppAwaitIdleRequest.FromString,
                    response_serializer=app__pb2.AppEmpty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tap.v1.AppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tap.v1.AppService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Install(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/Install',
            app__pb2.AppInstallRequest.SerializeToString,
            app__pb2.AppEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Uninstall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/Uninstall',
            app__pb2.AppRequest.SerializeToString,
            app__pb2.AppEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsInstalled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/IsInstalled',
            app__pb2.AppRequest.SerializeToString,
            app__pb2.AppBool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/ForceStop',
            app__pb2.AppRequest.SerializeToString,
            app__pb2.AppEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/ClearData',
            app__pb2.AppRequest.SerializeToString,
            app__pb2.AppEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/GrantPermission',
            app__pb2.AppGrantRequest.SerializeToString,
            app__pb2.AppEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Launch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/Launch',
            app__pb2.AppLaunchRequest.SerializeToString,
            app__pb2.AppEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ColdLaunch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/ColdLaunch',
            app__pb2.AppLaunchRequest.SerializeToString,
            app__pb2.ProcessIdentity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/Process',
            app__pb2.AppRequest.SerializeToString,
            app__pb2.ProcessIdentity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsRunning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/IsRunning',
            app__pb2.AppRequest.SerializeToString,
            app__pb2.AppBool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AwaitIdle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.AppService/AwaitIdle',
            app__pb2.AppAwaitIdleRequest.SerializeToString,
            app__pb2.AppEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
