# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x06tap.v1\"J\n\nAppRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0cpackage_name\x18\x02 \x01(\t\x12\x12\n\ntimeout_ms\x18\x03 \x01(\x03\"F\n\x11\x41ppInstallRequest\x12\x1f\n\x03\x61pp\x18\x01 \x01(\x0b\x32\x12.tap.v1.AppRequest\x12\x10\n\x08\x61pk_path\x18\x02 \x01(\t\"F\n\x0f\x41ppGrantRequest\x12\x1f\n\x03\x61pp\x18\x01 \x01(\x0b\x32\x12.tap.v1.AppRequest\x12\x12\n\npermission\x18\x02 \x01(\t\"W\n\x10\x41ppLaunchRequest\x12\x1f\n\x03\x61pp\x18\x01 \x01(\x0b\x32\x12.tap.v1.AppRequest\x12\x15\n\x08\x61\x63tivity\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_activity\"M\n\x13\x41ppAwaitIdleRequest\x12\x1f\n\x03\x61pp\x18\x01 \x01(\x0b\x32\x12.tap.v1.AppRequest\x12\x15\n\rstable_for_ms\x18\x02 \x01(\x03\"3\n\x0fProcessIdentity\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x13\n\x0bstart_token\x18\x02 \x01(\t\"\x18\n\x07\x41ppBool\x12\r\n\x05value\x18\x01 \x01(\x08\"\n\n\x08\x41ppEmpty2\xec\x04\n\nAppService\x12\x36\n\x07Install\x12\x19.tap.v1.AppInstallRequest\x1a\x10.tap.v1.AppEmpty\x12\x31\n\tUninstall\x12\x12.tap.v1.AppRequest\x1a\x10.tap.v1.AppEmpty\x12\x32\n\x0bIsInstalled\x12\x12.tap.v1.AppRequest\x1a\x0f.tap.v1.AppBool\x12\x31\n\tForceStop\x12\x12.tap.v1.AppRequest\x1a\x10.tap.v1.AppEmpty\x12\x31\n\tClearData\x12\x12.tap.v1.AppRequest\x1a\x10.tap.v1.AppEmpty\x12<\n\x0fGrantPermission\x12\x17.tap.v1.AppGrantRequest\x1a\x10.tap.v1.AppEmpty\x12\x34\n\x06Launch\x12\x18.tap.v1.AppLaunchRequest\x1a\x10.tap.v1.AppEmpty\x12?\n\nColdLaunch\x12\x18.tap.v1.AppLaunchRequest\x1a\x17.tap.v1.ProcessIdentity\x12\x36\n\x07Process\x12\x12.tap.v1.AppRequest\x1a\x17.tap.v1.ProcessIdentity\x12\x30\n\tIsRunning\x12\x12.tap.v1.AppRequest\x1a\x0f.tap.v1.AppBool\x12:\n\tAwaitIdle\x12\x1b.tap.v1.AppAwaitIdleRequest\x1a\x10.tap.v1.AppEmptyB$\n\x16\x63om.company.tap.api.v1B\x08\x41ppProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.company.tap.api.v1B\010AppProtoP\001'
  _globals['_APPREQUEST']._serialized_start=21
  _globals['_APPREQUEST']._serialized_end=95
  _globals['_APPINSTALLREQUEST']._serialized_start=97
  _globals['_APPINSTALLREQUEST']._serialized_end=167
  _globals['_APPGRANTREQUEST']._serialized_start=169
  _globals['_APPGRANTREQUEST']._serialized_end=239
  _globals['_APPLAUNCHREQUEST']._serialized_start=241
  _globals['_APPLAUNCHREQUEST']._serialized_end=328
  _globals['_APPAWAITIDLEREQUEST']._serialized_start=330
  _globals['_APPAWAITIDLEREQUEST']._serialized_end=407
  _globals['_PROCESSIDENTITY']._serialized_start=409
  _globals['_PROCESSIDENTITY']._serialized_end=460
  _globals['_APPBOOL']._serialized_start=462
  _globals['_APPBOOL']._serialized_end=486
  _globals['_APPEMPTY']._serialized_start=488
  _globals['_APPEMPTY']._serialized_end=498
  _globals['_APPSERVICE']._serialized_start=501
  _globals['_APPSERVICE']._serialized_end=1121
# @@protoc_insertion_point(module_scope)
