# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import client_connection_pb2 as client__connection__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in client_connection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientConnectionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/tap.v1.ClientConnectionService/Connect',
                request_serializer=client__connection__pb2.ConnectRequest.SerializeToString,
                response_deserializer=client__connection__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Observe = channel.unary_stream(
                '/tap.v1.ClientConnectionService/Observe',
                request_serializer=client__connection__pb2.ObserveRequest.SerializeToString,
                response_deserializer=client__connection__pb2.ObserveResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/tap.v1.ClientConnectionService/Disconnect',
                request_serializer=client__connection__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=client__connection__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/tap.v1.ClientConnectionService/Info',
                request_serializer=client__connection__pb2.InfoRequest.SerializeToString,
                response_deserializer=client__connection__pb2.InfoResponse.FromString,
                _registered_method=True)


class ClientConnectionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Long-lived stream the client keeps open for the life of the connection; it must be opened
        shortly after Connect. Its end is the liveness signal: the stream ending (either side)
        disconnects the client. The first event is `observing`; a daemon-initiated disconnect sends
        `closing` and then completes the stream normally.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientConnectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=client__connection__pb2.ConnectRequest.FromString,
                    response_serializer=client__connection__pb2.ConnectResponse.SerializeToString,
            ),
            'Observe': grpc.unary_stream_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=client__connection__pb2.ObserveRequest.FromString,
                    response_serializer=client__connection__pb2.ObserveResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=client__connection__pb2.DisconnectRequest.FromString,
                    response_serializer=client__connection__pb2.DisconnectResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=client__connection__pb2.InfoRequest.FromString,
                    response_serializer=client__connection__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tap.v1.ClientConnectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tap.v1.ClientConnectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientConnectionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.ClientConnectionService/Connect',
            client__connection__pb2.ConnectRequest.SerializeToString,
            client__connection__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tap.v1.ClientConnectionService/Observe',
            client__connection__pb2.ObserveRequest.SerializeToString,
            client__connection__pb2.ObserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.ClientConnectionService/Disconnect',
            client__connection__pb2.DisconnectRequest.SerializeToString,
            client__connection__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.ClientConnectionService/Info',
            client__connection__pb2.InfoRequest.SerializeToString,
            client__connection__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
