# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client_connection.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'client_connection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63lient_connection.proto\x12\x06tap.v1\"\x1e\n\x0e\x43onnectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"/\n\x0f\x43onnectResponse\x12\x1c\n\x14\x63lient_connection_id\x18\x01 \x01(\t\".\n\x0eObserveRequest\x12\x1c\n\x14\x63lient_connection_id\x18\x01 \x01(\t\")\n\tObserving\x12\x1c\n\x14\x63lient_connection_id\x18\x01 \x01(\t\"\x0b\n\tHeartbeat\"\x19\n\x07\x43losing\x12\x0e\n\x06reason\x18\x01 \x01(\t\"\xa3\x01\n\x0fObserveResponse\x12\x13\n\x0b\x61t_epoch_ms\x18\x01 \x01(\x03\x12&\n\tobserving\x18\x02 \x01(\x0b\x32\x11.tap.v1.ObservingH\x00\x12&\n\theartbeat\x18\x03 \x01(\x0b\x32\x11.tap.v1.HeartbeatH\x00\x12\"\n\x07\x63losing\x18\x04 \x01(\x0b\x32\x0f.tap.v1.ClosingH\x00\x42\x07\n\x05\x65vent\"1\n\x11\x44isconnectRequest\x12\x1c\n\x14\x63lient_connection_id\x18\x01 \x01(\t\"7\n\x12\x44isconnectResponse\x12!\n\x19\x61ttached_devices_detached\x18\x01 \x01(\x05\"\r\n\x0bInfoRequest\"\xa9\x01\n\x0cInfoResponse\x12\x16\n\x0e\x64\x61\x65mon_version\x18\x01 \x01(\t\x12\x15\n\rhost_build_id\x18\x02 \x01(\t\x12\x18\n\x10protocol_version\x18\x03 \x01(\t\x12\x16\n\x0e\x61\x64\x62_executable\x18\x04 \x01(\t\x12\x11\n\tstate_dir\x18\x05 \x01(\t\x12\x18\n\x10\x64river_available\x18\x06 \x01(\x08\x12\x0b\n\x03pid\x18\x07 \x01(\x03\x32\x8b\x02\n\x17\x43lientConnectionService\x12:\n\x07\x43onnect\x12\x16.tap.v1.ConnectRequest\x1a\x17.tap.v1.ConnectResponse\x12<\n\x07Observe\x12\x16.tap.v1.ObserveRequest\x1a\x17.tap.v1.ObserveResponse0\x01\x12\x43\n\nDisconnect\x12\x19.tap.v1.DisconnectRequest\x1a\x1a.tap.v1.DisconnectResponse\x12\x31\n\x04Info\x12\x13.tap.v1.InfoRequest\x1a\x14.tap.v1.InfoResponseB;\n io.github.noamcohen48.tap.api.v1B\x15\x43lientConnectionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_connection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n io.github.noamcohen48.tap.api.v1B\025ClientConnectionProtoP\001'
  _globals['_CONNECTREQUEST']._serialized_start=35
  _globals['_CONNECTREQUEST']._serialized_end=65
  _globals['_CONNECTRESPONSE']._serialized_start=67
  _globals['_CONNECTRESPONSE']._serialized_end=114
  _globals['_OBSERVEREQUEST']._serialized_start=116
  _globals['_OBSERVEREQUEST']._serialized_end=162
  _globals['_OBSERVING']._serialized_start=164
  _globals['_OBSERVING']._serialized_end=205
  _globals['_HEARTBEAT']._serialized_start=207
  _globals['_HEARTBEAT']._serialized_end=218
  _globals['_CLOSING']._serialized_start=220
  _globals['_CLOSING']._serialized_end=245
  _globals['_OBSERVERESPONSE']._serialized_start=248
  _globals['_OBSERVERESPONSE']._serialized_end=411
  _globals['_DISCONNECTREQUEST']._serialized_start=413
  _globals['_DISCONNECTREQUEST']._serialized_end=462
  _globals['_DISCONNECTRESPONSE']._serialized_start=464
  _globals['_DISCONNECTRESPONSE']._serialized_end=519
  _globals['_INFOREQUEST']._serialized_start=521
  _globals['_INFOREQUEST']._serialized_end=534
  _globals['_INFORESPONSE']._serialized_start=537
  _globals['_INFORESPONSE']._serialized_end=706
  _globals['_CLIENTCONNECTIONSERVICE']._serialized_start=709
  _globals['_CLIENTCONNECTIONSERVICE']._serialized_end=976
# @@protoc_insertion_point(module_scope)
