# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: connection.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'connection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onnection.proto\x12\x06tap.v1\"%\n\x15OpenConnectionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"/\n\x16OpenConnectionResponse\x12\x15\n\rconnection_id\x18\x01 \x01(\t\"&\n\rAttachRequest\x12\x15\n\rconnection_id\x18\x01 \x01(\t\"7\n\x0f\x43onnectionEvent\x12\x13\n\x0b\x61t_epoch_ms\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x16\x43loseConnectionRequest\x12\x15\n\rconnection_id\x18\x01 \x01(\t\"2\n\x17\x43loseConnectionResponse\x12\x17\n\x0fsessions_closed\x18\x01 \x01(\x05\"\r\n\x0bInfoRequest\"\x9b\x01\n\x0cInfoResponse\x12\x17\n\x0fservice_version\x18\x01 \x01(\t\x12\x15\n\rhost_build_id\x18\x02 \x01(\t\x12\x18\n\x10protocol_version\x18\x03 \x01(\t\x12\x16\n\x0e\x61\x64\x62_executable\x18\x04 \x01(\t\x12\x11\n\tstate_dir\x18\x05 \x01(\t\x12\x16\n\x0e\x62undled_driver\x18\x06 \x01(\x08\x32\x93\x02\n\x11\x43onnectionService\x12\x45\n\x04Open\x12\x1d.tap.v1.OpenConnectionRequest\x1a\x1e.tap.v1.OpenConnectionResponse\x12:\n\x06\x41ttach\x12\x15.tap.v1.AttachRequest\x1a\x17.tap.v1.ConnectionEvent0\x01\x12H\n\x05\x43lose\x12\x1e.tap.v1.CloseConnectionRequest\x1a\x1f.tap.v1.CloseConnectionResponse\x12\x31\n\x04Info\x12\x13.tap.v1.InfoRequest\x1a\x14.tap.v1.InfoResponseB+\n\x16\x63om.company.tap.api.v1B\x0f\x43onnectionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.company.tap.api.v1B\017ConnectionProtoP\001'
  _globals['_OPENCONNECTIONREQUEST']._serialized_start=28
  _globals['_OPENCONNECTIONREQUEST']._serialized_end=65
  _globals['_OPENCONNECTIONRESPONSE']._serialized_start=67
  _globals['_OPENCONNECTIONRESPONSE']._serialized_end=114
  _globals['_ATTACHREQUEST']._serialized_start=116
  _globals['_ATTACHREQUEST']._serialized_end=154
  _globals['_CONNECTIONEVENT']._serialized_start=156
  _globals['_CONNECTIONEVENT']._serialized_end=211
  _globals['_CLOSECONNECTIONREQUEST']._serialized_start=213
  _globals['_CLOSECONNECTIONREQUEST']._serialized_end=260
  _globals['_CLOSECONNECTIONRESPONSE']._serialized_start=262
  _globals['_CLOSECONNECTIONRESPONSE']._serialized_end=312
  _globals['_INFOREQUEST']._serialized_start=314
  _globals['_INFOREQUEST']._serialized_end=327
  _globals['_INFORESPONSE']._serialized_start=330
  _globals['_INFORESPONSE']._serialized_end=485
  _globals['_CONNECTIONSERVICE']._serialized_start=488
  _globals['_CONNECTIONSERVICE']._serialized_end=763
# @@protoc_insertion_point(module_scope)
