# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import connection_pb2 as connection__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in connection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConnectionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.unary_unary(
                '/tap.v1.ConnectionService/Open',
                request_serializer=connection__pb2.OpenConnectionRequest.SerializeToString,
                response_deserializer=connection__pb2.OpenConnectionResponse.FromString,
                _registered_method=True)
        self.Attach = channel.unary_stream(
                '/tap.v1.ConnectionService/Attach',
                request_serializer=connection__pb2.AttachRequest.SerializeToString,
                response_deserializer=connection__pb2.ConnectionEvent.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/tap.v1.ConnectionService/Close',
                request_serializer=connection__pb2.CloseConnectionRequest.SerializeToString,
                response_deserializer=connection__pb2.CloseConnectionResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/tap.v1.ConnectionService/Info',
                request_serializer=connection__pb2.InfoRequest.SerializeToString,
                response_deserializer=connection__pb2.InfoResponse.FromString,
                _registered_method=True)


class ConnectionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Open(self, request, context):
        """Creates a connection; call Attach next.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attach(self, request, context):
        """Long-lived stream the client keeps open for the life of the connection. Server-side
        cancellation of this stream is the liveness signal; the messages are informational.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Closes every session of the connection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Service version, protocol version and configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=connection__pb2.OpenConnectionRequest.FromString,
                    response_serializer=connection__pb2.OpenConnectionResponse.SerializeToString,
            ),
            'Attach': grpc.unary_stream_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=connection__pb2.AttachRequest.FromString,
                    response_serializer=connection__pb2.ConnectionEvent.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=connection__pb2.CloseConnectionRequest.FromString,
                    response_serializer=connection__pb2.CloseConnectionResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=connection__pb2.InfoRequest.FromString,
                    response_serializer=connection__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tap.v1.ConnectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tap.v1.ConnectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConnectionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.ConnectionService/Open',
            connection__pb2.OpenConnectionRequest.SerializeToString,
            connection__pb2.OpenConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tap.v1.ConnectionService/Attach',
            connection__pb2.AttachRequest.SerializeToString,
            connection__pb2.ConnectionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.ConnectionService/Close',
            connection__pb2.CloseConnectionRequest.SerializeToString,
            connection__pb2.CloseConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tap.v1.ConnectionService/Info',
            connection__pb2.InfoRequest.SerializeToString,
            connection__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
