# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x06tap.v1\"\xaf\x01\n\x0b\x44\x65viceEntry\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\"\n\x05state\x18\x02 \x01(\x0e\x32\x13.tap.v1.DeviceState\x12\x1f\n\x12held_by_connection\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x1e\n\x11quarantine_reason\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x15\n\x13_held_by_connectionB\x14\n\x12_quarantine_reason\"\x14\n\x12ListDevicesRequest\";\n\x13ListDevicesResponse\x12$\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x13.tap.v1.DeviceEntry*{\n\x0b\x44\x65viceState\x12\x1c\n\x18\x44\x45VICE_STATE_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x44\x45VICE_FREE\x10\x01\x12\x11\n\rDEVICE_LEASED\x10\x02\x12\x16\n\x12\x44\x45VICE_QUARANTINED\x10\x03\x12\x12\n\x0e\x44\x45VICE_OFFLINE\x10\x04\x32W\n\rDeviceService\x12\x46\n\x0bListDevices\x12\x1a.tap.v1.ListDevicesRequest\x1a\x1b.tap.v1.ListDevicesResponseB\'\n\x16\x63om.company.tap.api.v1B\x0b\x44\x65viceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.company.tap.api.v1B\013DeviceProtoP\001'
  _globals['_DEVICESTATE']._serialized_start=285
  _globals['_DEVICESTATE']._serialized_end=408
  _globals['_DEVICEENTRY']._serialized_start=25
  _globals['_DEVICEENTRY']._serialized_end=200
  _globals['_LISTDEVICESREQUEST']._serialized_start=202
  _globals['_LISTDEVICESREQUEST']._serialized_end=222
  _globals['_LISTDEVICESRESPONSE']._serialized_start=224
  _globals['_LISTDEVICESRESPONSE']._serialized_end=283
  _globals['_DEVICESERVICE']._serialized_start=410
  _globals['_DEVICESERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
